### ISSUE TITLE
All Mathematical Algo are missing

### ISSUE THREAD

**Issue by p4nth3r-5237** [smilegupta/Mastering_DSA#4]
Like Pigeon Hole, closed form, Voronoi diagram, Matrix Power, Numerical Integration, NIM Algo
Can i add these algo??

**Comment by smilegupta** [comment]
hey i will add it!! not at all a isssue!! if you have the codes..you can too add them!! i will merge the stuff in my repo

**Comment by smilegupta** [comment]
hey yes please feel free to add them



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
21/03/20,
01:15:35 am
